name: Build & Deploy to Hostinger (FTP)

on:
  push:
    branches: [ "main" ]  # adjust if your branch is different
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ secrets.NODE_VERSION || '20' }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ${{ secrets.FTP_PROTOCOL }}
          local-dir: ${{ secrets.BUILD_DIR || 'dist' }}/
          server-dir: ${{ secrets.FTP_REMOTE_DIR }}/
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/node_modules/**
            **/.DS_Store
