name: Build & Deploy to Hostinger (FTP, pnpm)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'   # cache based on pnpm-lock.yaml

      - name: Enable corepack & set pnpm version
        run: |
          corepack enable
          # If your package.json has "packageManager": "pnpm@x.y.z", corepack will use that version.
          # Otherwise you can pin a version explicitly:
          # corepack prepare pnpm@9.12.0 --activate

      - name: Install dependencies (pnpm)
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: List build output (debug)
        run: ls -la dist

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ${{ secrets.FTP_PROTOCOL }}   # ftps recommended
          # If Hostinger gave you a non-default port, add:
          # port: ${{ secrets.FTP_PORT }}
          local-dir: dist/
          server-dir: ${{ secrets.FTP_REMOTE_DIR }}/
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/node_modules/**
            **/.DS_Store
